### ISSUE TITLE
does not work on Windows 10

### ISSUE THREAD

**Issue by maxzod** [devmuaz/flutter-image-assets#1]
after picking the folder noting happens

OS :: windows 10
![image](https://user-images.githubusercontent.com/47630729/143317545-a4f2c1d6-5688-4e3f-a62d-44df47bccc1c.png)

**Comment by devmuaz** [comment]
Thank you @maxzod for opening this issue, it has been fixed in version `0.0.3`.
Try updating it out and hopefully it will work just fine ❤️
